### ISSUE TITLE
Use with files outside of public dir

### ISSUE THREAD

**Issue by foaly-nr1** [snowcap/SnowcapImBundle#15]
Sadly, this only works with files living in the public directory. When working with sensitive files, I prefer storing them outside the public directory though.

**Comment by Moinax** [comment]
You are right, we are thinking about making the base path and subpath pattern fully customizable in a few days.

**Comment by Moinax** [comment]
This has been fixed in 5ac2672870e54b9a1a2eeb50528848b6599aff59 as part of v1.0.2 release
